name: Market Trading Data External Adapter
description: Chainlink External Adapter for Stock Market Pricing Check
node_identifier: fsmarket
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: OpenWeather
    url: https://openweathermap.org/
parameters:
  - endpoint
  - cityID
  - days
